### ISSUE TITLE
Supported method of embedding wasm file?

### ISSUE THREAD

**Issue by mstade** [sql-js/sql.js#312]
Hi, great project!

Is there a way to configure `initSqlJs` to look for an embedded arraybuffer of the wasm file, and thus avoid the extra fetch?

I know this may sound strange, but I have a use case where I'm embedding a full app in a single html file, and that's obviously how it's run as well, but simply loading the html file in a browser. Thus, an extra fetch isn't really possible for several reasons, but I can't seem to figure out if there's a supported way to do this. I worked around it by doing something like this:

```javascript
// sql.js embedded in another script element
// sqlWASM is loaded as a buffer, converted to a simple array of numbers, and then a Uin8array is built from this array, and used as the return from our `fetch` override below

const sqlWASM = Uint8Array.from([${sqlWASM}])

config = {
  locateFile: filename => 'embedded'
}

const actualFetch = window.fetch
window.fetch = (url, ...rest) => {
  if (url === 'embedded') {
    return Promise.resolve({
      ok: true,
      arrayBuffer: () => sqlWASM.buffer
    })
  } else {
    actualFetch(url, ...rest)
  }
}
```

This works, really well actually. I can now load a single html file that has sql.js fully embedded, with no additional dependencies. Load time is pretty good too, about half a second on average – worst timing I've seen was around 750ms. Since bandwidth isn't an issue, it comes down to initialization time. Anything sub-second is magical, anything <5 seconds is fully acceptable, and only at 5+ seconds do we consider there being an issue with load time.

Anyway, it's obviously a bit of an edge case, but if there's some kind of supported way of doing this I'd probably rather do that. Penny for your thoughts!

**Comment by lovasoa** [comment]
Hi ! 

A nice thing to do when you need to have a single HTML file is to encode binary resources as pixels in PNG files. This has several advantages over what you are doing:

 - Thanks to PNG using deflate, the binary data is compressed
 - The parsing and decompression does not block scripts: the browser is free to do it in parallel, since the data is just an ordinary image.
 

I published a library to to that today. See: https://github.com/lovasoa/bin2png

<img width="519" alt="image" src="https://user-images.githubusercontent.com/552629/69986946-b9f1ab00-153e-11ea-8f64-0275918d7dde.png">

**Comment by lovasoa** [comment]
Here is a demo using sql.js with bin2png : https://bin2png-example.netlify.com/

I would be curious to know how it compares to what you had previously.

**Comment by mstade** [comment]
That is *wild*, never crossed my mind to use images like that! Thanks a lot for the suggestion @lovasoa, definitely going to give this a spin. Coming back to the original question, I noticed [this snippet][1] in your example:

```javascript
let fileBlobs = fileContents.map((x, i) => URL.createObjectURL(new Blob([x], fileImgs[i].dataset)));
let SQL = await initSqlJs({
    locateFile: f => fileBlobs[fileNames.indexOf(f)] || f
});
```

Is that essentially the answer to my question? Instead of overriding fetch, return an object URL and fetch will know what to do with it? Or am I reading this wrong? I'll have a look and try to figure it out, but any pointers you may be willing to give is much appreciated – clearly you have a better understanding of all this than I do! :o)

Absolute mad genius techniques on display here buddy, I definitely learned something new! Much, *much* appreciated – thank you!!

[1]: https://github.com/lovasoa/bin2png/blob/master/example/script.js#L12-L15

**Comment by lovasoa** [comment]
> Is that essentially the answer to my question?

Correct. The object URL is understood by fetch. Don't forget to pass the `options` argument to the `Blob` constructor to specify the mime type of the data (application/wasm in this case). This makes the instantiation of the wasm module more performant.

**Comment by humblecoder** [comment]
> let fileBlobs = fileContents.map((x, i) => URL.createObjectURL(new Blob([x], fileImgs[i].dataset))); let SQL = await initSqlJs({ locateFile: f => fileBlobs[fileNames.indexOf(f)] || f });

@mstade @lovasoa I realize this issue is closed, but would you mind providing a bit more context on this solution?  For example, where are `fileContents` and `fileImgs` getting their data?  It seems like you guys dove into the middle of the solution and it's not immediately clear how you got there.  🤔 

FYI, I'm working with Capacitor/Cordova applications but using SQL.JS because I prefer to keep the SQL solutions to the browser (as opposed to something like `capacitor-community/sqlite`), as SQL.JS seems more convenient during development, and speed won't be super critical in production.  I'm also trying to keep everything local/bundled rather than rely on CDN.

Thanks for all your work with this either way.

**Comment by SMUsamaShah** [comment]
png2bin and then bin2png works but if you have base64 string already then that works too.

I used https://github.com/BillKek/wasm2js_let_static to convert `sql-wasm.wasm v1.8.0` to base64.

Then loaded it like this

```javascript
    const wasm_strbuffer = atob(SQLBASE64);
    let wasm_codearray = new Uint8Array(wasm_strbuffer.length);
    for (var i in wasm_strbuffer) wasm_codearray[i] = wasm_strbuffer.charCodeAt(i);

    const sqlPromise = initSqlJs({
        locateFile: filename => URL.createObjectURL(new Blob([wasm_codearray], { type: 'application/wasm' }))
    });
    const dataPromise = fetch("mysqlite.db").then(res => res.arrayBuffer());
    Promise.all([sqlPromise, dataPromise]).then((data) => {
        const SQL = data[0];
        const buf = data[1];
        const db = new SQL.Database(new Uint8Array(buf));
        dbLoaded(db);
    });
```

and it just works.

Base64 wasm gist https://gist.github.com/SMUsamaShah/358fba159cb41fe469fc61e7db444c0e

**Comment by lovasoa** [comment]
base64 is less efficient, and decoding it completely blocks the main thread.

**Comment by SMUsamaShah** [comment]
Isn't that usually a one time operation? As in png or Base64, you will only be loading the wasm module just once? Unless you happen to do it in the middle of something or on low end devices it should not matter too much, no?

**Comment by lovasoa** [comment]
It will happen on every page lost
