### ISSUE TITLE
Uncaught Error: near ":param": syntax error

### ISSUE THREAD

**Issue by soaxelbrooke** [sql-js/sql.js#401]
The following query  is valid SQL, but results in an error:

```javascript
db.exec("select count(*) from foo where bar in :param;", {":param": ["baz", "baffle"]})
```
Inserting the param literal works, though:

```javascript
db.exec("select count(*) from foo where bar in ('baz', 'baffle');")
```

**Comment by lovasoa** [comment]
Hello, 
sql.js is "just" SQLite compiled to JavaScript. Since SQLite does not support binding an array values to a statement parameter, not does sql.js. There are multiple ways to work around this though. Have a look at [this so question](https://stackoverflow.com/questions/4788724/sqlite-bind-list-of-values-to-where-col-in-prm) for example.
