### ISSUE TITLE
Abort running query

### ISSUE THREAD

**Issue by twoxfh** [sql-js/sql.js#461]
Does anyone know how to abort a running query? 

I added the sqlite3_interruput to SQL-JS, however since the underlying code is really synchronous, this really does nothing. I found an [abort controller](https://github.com/phiresky/sql.js-httpvfs/issues/3), issue with great discussion but without any outcome. There is a pragma busy-timeout which does not seem to abort the query. The only other method I have used is terminating the worker, however, then I have to reload the database. 

Any thoughts?

**Comment by lovasoa** [comment]
It is not possible to abort a running query in the current sql.js. Your best bet for the moment is to kill the worker. 

You could try to implement that using emscripten's pthread support and sqlite3_interrupt, but this would probably be a lot of work, make the library slower, require you to serve your pages with custom headers, and not work on all browsers...

**Comment by rhashimoto** [comment]
Note that you _can_ interrupt a query between output rows, simply by stopping calling `step()`. The problem is interrupting a query in the middle of a step.

I think there might be _one_ way to do that with the current sql.js, though it is pretty limited. If you use [`create_function`](https://sql.js.org/documentation/Database.html#%255B%2522create_function%2522%255D) to define a custom SQL function, then throwing an exception from that function looks like it will abort the query that uses it. You would have to construct your query to call the function repeatedly, and the function needs to decide synchronously whether or not to throw. So perhaps technically possible for some narrow use cases.

If you're not opposed to forking sql.js and hacking the SQLite C source, you could find a spot in the SQLite code to inject a call to Javascript and conditionally return an error code (somewhere in the pager might work). Basically a similar approach as above but one that works with any query.

**Comment by twoxfh** [comment]
@rhashimoto great insight. I was able to make a sub select as a start time, use time in the main select, calculate the difference in time, then throw the Error which halted the query. Convoluted but worked. 

Thanks, hopefully over time it wont get so convoluted.
