### ISSUE TITLE
Error: Out of Memory in 1.5.0 when creating database

### ISSUE THREAD

**Issue by timroes** [sql-js/sql.js#463]
I tried to upgrade `sql.js` in one of my projects from 1.4.0 to 1.5.0. This caused the project to no longer work (no other dependencies upgraded at the same time), but fail with an `Error: Out of memory` failure, when trying to call `new sqlite.Database()`.

I've created a minimal reproducible example: https://codesandbox.io/s/sqljs-150-oom-ptd8l

```js
import initSqlJs from "sql.js";

initSqlJs({
  locateFile: (file) => `https://sql.js.org/dist/${file}`
}).then((sqlite) => {
  new sqlite.Database();
});
```

The `new sqlite.Database()` call will fail with an `out of memory` error.

I can reproduce the behavior in Chromium and Firefox on my machine (Linux).

**Comment by lovasoa** [comment]
Can you provide a minimal example that reproduces the error?

**Comment by timroes** [comment]
Could you please clarify how the above minimal example isn't reproducing this but for you? You don't get the error with it?

**Comment by lovasoa** [comment]
No I don't

![image](https://user-images.githubusercontent.com/552629/124442362-f3bf0f00-dd7c-11eb-9f30-b30b8f4649b8.png)

**Comment by lovasoa** [comment]
There is an always up-to-date version of sql.js running as a demo on https://sql.js.org/examples/GUI/

**Comment by timroes** [comment]
@lovasoa Can you try pressing the `refresh` button in the "browser view" on the above link. That's only what makes the error overlay show up for me:

![screenshot-20210705-105011](https://user-images.githubusercontent.com/877229/124444406-db4ff400-dd7e-11eb-969a-8e9c2c6a4b2e.png)

The linked example actually does not cause that error for me, though this is using the "worker" variation, while my example is using the WASM one directly. I can consitantly reproduce it on the above codesandbox, when pressing the refresh button in the browser preview window (the same as on my (closed-sourced) project). Does pressing that button make it reproducible for you?

**Comment by timroes** [comment]
Alternative open that link directly https://ptd8l.csb.app/ and checking the console output is also 100% reliable failing for me.

**Comment by lovasoa** [comment]
Yes, I can see the error on https://ptd8l.csb.app/

**Comment by rhashimoto** [comment]
@timroes You're using a `sql-wasm.js` and `sql-wasm.wasm` from two different places, one from your package manager and the other from `sql.js.org`. These files are generated together by the build process and my guess is that they are not in sync. Even though the sql.js package versions are the same, I suspect they have been built with different Emscripten SDK versions. If you diff the `sql-wasm.js` file your app is using and the `sql-wasm.js` file from `sql.js.org/dist` (ignoring the differences due to bundling) you can see that those files are not quite the same. I'm speculating, but I wonder if there might be some incompatible assumptions about the .wasm file buried there.

Are you loading the .wasm file from `sql.js.org` in your local tests as well? If so, I would try extracting the `sql-wasm.wasm` file from your local package, host it somewhere, and  point `locateFile` there to see if that works any better.

**Comment by timroes** [comment]
@rhashimoto In my project I actually use both files from the node_modules. I was just not sure how to reproduce the very same in codesandbox thus used the CDN to get the WASM there. If it's not reproducible for you with loading both from `node_modules` please let me know, then I'll try to get a separate git repo up reproducing the behavior for me.

**Comment by lovasoa** [comment]
This error can occur if you are trying to create a large number of databases. 
I'm not sure exactly how codesandbox works, and it is hard to inspect because it seems to be using eval. It may be linked to how they implement hot reload.

In your own application, are you sure you call initSqlJs only once ? This kind of bug is easy to introduce in a react codebase with incorrectly configured hooks for instance, where you would recreate a new database on every render.
And if the bug occurs only in dev, it may be linked to hot reload in your project.

Not closing this issue, because there may be an underlying issue in sql.js itself where it leaks memory.

**Comment by timroes** [comment]
Pretty sure it's only called once and I purposfully disabled hot reload because - as you mentioned - it was not easily working with sql.js. Though as mentioned above: the very same code worked fine in 1.4.0, I solely did upgrade to 1.5.0 and it stopped working. Let me get a reproducible example outside of codesandbox up, making sure to use both assets from the npm 1.5.0 version and link that here.

**Comment by timroes** [comment]
I've tried to create a reproducible minimal example using create react app, and it actually seems to work in there. I'll try to investigate further why using create react app in my other application (where I have pretty much the same setup) is failing, and also why Codesandbox, which uses a completely different system (and different bundler -  parcel - in my example above) is failing in exactly the same way.

I'll close this for now, since it seems to be rather some side-effect of the build infrastructure/bundling system, and will only reopen if there's anything that I feel would be addressable on sql.js-side.

**Comment by timroes** [comment]
Stupid me! Failure was on my side. `yarn upgrade-interactive` does _not_ call the `postinstall` script from the `package.json` after it's done installing the upgrades (only `yarn install` does), which is the script which handles the WASM files in my case, thus I actually had the mismatch between `sql.js` and the WASM file. Thanks for your pointers here :green_heart:

**Comment by lovasoa** [comment]
@timroes 
That is none of my business, but it looks like your setup could be improved. You should not have to introduce a custom script to copy the wasm file, just configure your bundler so that it can find it. There is an example of how to set that up in https://github.com/sql-js/react-sqljs-demo

This should prevent you from bumping into this kind of problems again in the future.

**Comment by timroes** [comment]
@lovasoa Thanks for the reminder. I initially didn't do that, because it didn't work without using craco or some other CRA customizer, which I tried to avoid using. But I nowadays anyway have craco in for other reasons, so I should definitely switch that over to have webpack bundle it automatically for me.
