### ISSUE TITLE
Request for spatial support

### ISSUE THREAD

**Issue by MicheleFioretto** [sql-js/sql.js#59]
it would be great and very usefull the porting of sqllite spatial into sql.js
Do You think is it possible?

**Comment by sveta-wl** [comment]
Hi @lovasoa 
would it be possible to update the rtree branch with latest master commits? This would be awesome!

Thank you in advance

**Comment by danielbarela** [comment]
@lovasoa  Is there a reason that -DSQLITE_ENABLE_RTREE=1 cannot be added to the Makefile for this library?

**Comment by lovasoa** [comment]
because we don't want to enable it by default

**Comment by lovasoa** [comment]
if you want it, then you can compile sql.js, it's not difficult

**Comment by danielbarela** [comment]
I have compiled it. It is sitting in my repository. That isn't the issue.  Multiple people have asked for it. You build in other things like FTS3.  I just figured that maybe you would want to actually help out the people that are using your library.  But that's fine it is your repository.

**Comment by lovasoa** [comment]
This is not my repository, and I'm sorry if I sounded rude. Shipping rarely-used features by default is not a good idea because it makes the distributed wasm file heavier. 
We could distribute several versions of sql.js using GitHub releases, though. If you want to contribute to our github action workflows and implement multiple releases, I'll be happy to review your work.

**Comment by hoogw** [comment]
In 2020, can you show the document or guide on 
               **### How to use rtree spatial function in this js lib?**

**Comment by lovasoa** [comment]
If someone is interested in writing such a guide, please do so in [the wiki](https://github.com/sql-js/sql.js/wiki). We can then link to it from the README.
